### ISSUE TITLE
MapToIterable Exception

### ISSUE THREAD

**Issue by cmanou** [rossmartin/ionic2-alpha-scroll#7] opened 2016-11-21 01:36 UTC
I am getting the following  exception when I attempt to change the contents of the list

```
Error in ./IonAlphaScroll class IonAlphaScroll - inline template:5:6 caused by: Type MapToIterable is part of the declarations of 2 modules: TemplateModule and TemplateModule! Please consider moving MapToIterable to a higher module that imports TemplateModule and TemplateModule. You can also create a new NgModule that exports and includes MapToIterable then import that NgModule in TemplateModule and TemplateModule.
```
Set up is just an array of elements with property name on any updates i am calling the following

```
      this.triggerAlphaScrollChange++;
```

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v6.8.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by rossmartin** [comment] 2016-11-21 13:43
Thanks for reporting I'll take a look soon.  I'm having some issues running the app on an iOS device.  I can make a build successfully but there appears to be an issue compiling dynamic templates.  I think I'm going to have to use a different approach for compiling the template for the component because of the new AoT compiling.

![image](https://cloud.githubusercontent.com/assets/2498502/20484698/11354190-afbe-11e6-8147-cc55637878cf.png)

**Comment by vineetdpnd** [comment] 2016-11-21 15:48
Facing a similar issue. 

<img width="1058" alt="ionic2-app-ion-scroll-issue" src="https://cloud.githubusercontent.com/assets/17204129/20489217/d174a3e4-b02f-11e6-9c61-f8b0a51006d4.PNG">

**Comment by rossmartin** [comment] 2016-11-22 15:55
@vineetdpnd @cmanou This should be fixed in [1.0.7](https://github.com/rossmartin/ionic2-alpha-scroll/tree/1.0.7).  I've tested it with the [example I made](https://github.com/rossmartin/ionic2-alpha-scroll-example) but I'll wait to close this until I hear back.

**Comment by tabirkeland** [comment] 2016-11-29 18:36
Seeing the same issue using `1.0.7`

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.0
Xcode version: Not installed
```

**Comment by rossmartin** [comment] 2016-11-29 19:58
@tabirkeland @vineetdpnd 

I forgot to mention that there is an extra step on the install now.  Update your `src/app/main.prod.ts` and `src/app/app.module.ts` [shown here](https://github.com/rossmartin/ionic2-alpha-scroll#rc0-and-and-higher--)

Let me know if that solves the issue.  Thanks.

**Comment by tabirkeland** [comment] 2016-11-30 13:58
@rossmartin I included that step in my installation process when I was testing.

**Comment by rossmartin** [comment] 2016-11-30 15:28
@tabirkeland I'll look into it further.  I can't reproduce the issue in the [example I made](https://github.com/rossmartin/ionic2-alpha-scroll-example) unfortunately.

**Closed as completed** 2021-12-16 21:22 UTC
